name: carros
description: A new Flutter application.


publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^0.5.6
  http: ^0.12.2

  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.6
  cupertino_icons: ^0.1.3
  sqflite: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3
  mobx_codegen: ^0.4.0+1






flutter:


  uses-material-design: true



